const DEFAULT_PRODUCTS = [
  {id:1, name:'Jonge kaas', cat:'Hollandse kaas', unit:'st', std:9},
  {id:2, name:'Jong belegen', cat:'Hollandse kaas', unit:'st', std:9},
  {id:3, name:'Belegen', cat:'Hollandse kaas', unit:'st', std:12},
  {id:4, name:'Extra belegen', cat:'Hollandse kaas', unit:'st', std:2},
  {id:5, name:'Jubileum kaas', cat:'Hollandse kaas', unit:'st', std:3},
  {id:6, name:'Old special', cat:'Hollandse kaas', unit:'st', std:11},
  {id:7, name:'Oude dorpkaas', cat:'Hollandse kaas', unit:'st', std:3},
  {id:8, name:'Brokkel kaas', cat:'Hollandse kaas', unit:'st', std:1},
  {id:9, name:'30+ Jong belegen', cat:'Hollandse kaas', unit:'st', std:5},
  {id:10, name:'Gouwenaar 30+ pittig', cat:'Hollandse kaas', unit:'st', std:10},
  {id:11, name:'30+ extra gerijpt', cat:'Hollandse kaas', unit:'st', std:2},
  {id:12, name:'Boeren jong belegen', cat:'Hollandse kaas', unit:'st', std:1},
  {id:13, name:'Boeren belegen', cat:'Hollandse kaas', unit:'st', std:4},
  {id:14, name:'Boeren extra belegen', cat:'Hollandse kaas', unit:'st', std:4},
  {id:15, name:'Grand Cru', cat:'Hollandse kaas', unit:'st', std:12},
  {id:16, name:'Boeren oud', cat:'Hollandse kaas', unit:'st', std:1},
  {id:17, name:'Bio Belegen', cat:'Hollandse kaas', unit:'st', std:8},
  {id:18, name:'Bio extra belegen', cat:'Hollandse kaas', unit:'st', std:8},
  {id:19, name:'Biologische rauwmelkse boeren', cat:'Hollandse kaas', unit:'st', std:6},
  {id:20, name:'Komijn jong', cat:'Hollandse kaas', unit:'st', std:1},
  {id:21, name:'Komijn belegen', cat:'Hollandse kaas', unit:'st', std:2},
  {id:22, name:'Komijn oud', cat:'Hollandse kaas', unit:'st', std:1},
  {id:23, name:'Nagel kaas', cat:'Hollandse kaas', unit:'st', std:1},
  {id:24, name:'Geitenkaas aktie', cat:'Hollandse kaas', unit:'st', std:7},
  {id:25, name:'Geitenkaas pittig belegen', cat:'Hollandse kaas', unit:'st', std:3},
  {id:26, name:'Geitenkaas oud', cat:'Hollandse kaas', unit:'st', std:3},
  {id:27, name:'Eko Geitenkaas', cat:'Hollandse kaas', unit:'st', std:3},
  {id:28, name:'30+ geitenkaas', cat:'Hollandse kaas', unit:'st', std:2},
  {id:29, name:'Geit fenegriek', cat:'Hollandse kaas', unit:'st', std:0},
  {id:30, name:'Geit brandnetel', cat:'Hollandse kaas', unit:'st', std:0},
  {id:31, name:'Geit italiaanse kruiden', cat:'Hollandse kaas', unit:'st', std:0},
  {id:32, name:'Geit truffel (kruid)', cat:'Hollandse kaas', unit:'st', std:0},
  {id:33, name:'Schapenkaas jong', cat:'Hollandse kaas', unit:'st', std:1},
  {id:34, name:'Schapenkaas oud', cat:'Hollandse kaas', unit:'st', std:1},
  {id:35, name:'Boeren Leide 20+ zacht', cat:'Hollandse kaas', unit:'st', std:1},
  {id:36, name:'Boeren Leide 20+ pikant', cat:'Hollandse kaas', unit:'st', std:1},
  {id:37, name:'Maasdammer', cat:'Hollandse kaas', unit:'st', std:1},
  {id:38, name:'Tynjetaler', cat:'Hollandse kaas', unit:'st', std:2},
  {id:39, name:'Seizoenskaas (lente/herfst)', cat:'Hollandse kaas', unit:'st', std:1},
  {id:40, name:'Fenegriek', cat:'Hollandse kaas', unit:'st', std:1},
  {id:41, name:'Honing klaver', cat:'Hollandse kaas', unit:'st', std:1},
  {id:42, name:'Sedurre', cat:'Hollandse kaas', unit:'st', std:5},
  {id:43, name:'Truffelkaas', cat:'Hollandse kaas', unit:'st', std:5},
  {id:44, name:'Maaslander (minder zout)', cat:'Hollandse kaas', unit:'st', std:1},
  {id:45, name:'Schermermolen', cat:'Hollandse kaas', unit:'st', std:1},
  {id:46, name:'Boer\'n Jumbo', cat:'Hollandse kaas', unit:'½', std:0},
  {id:47, name:'Boeren kilo', cat:'Hollandse kaas', unit:'st', std:6},
  {id:48, name:'Edammers', cat:'Hollandse kaas', unit:'st', std:5},
  {id:49, name:'Roombrie', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:50, name:'Brie de Meaux', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:51, name:'Epoisses Coupe', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:52, name:'Gorgonzola Cremosa SCHEP', cat:'Buitenlandse kaas', unit:'st', std:3},
  {id:53, name:'Gorgonzola SCHEP truffel', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:54, name:'Gorgonzola', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:55, name:'Talleggio', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:56, name:'Delice de Bourgogne', cat:'Buitenlandse kaas', unit:'st', std:3},
  {id:57, name:'St agur', cat:'Buitenlandse kaas', unit:'st', std:4},
  {id:58, name:'Roquefort', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:59, name:'Blu 61', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:60, name:'Bleu stilton', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:61, name:'Camembert calvados', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:62, name:'Morbier', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:63, name:'Rambol nootmix', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:64, name:'Reblochon', cat:'Buitenlandse kaas', unit:'st', std:4},
  {id:65, name:'Tete de Moine', cat:'Buitenlandse kaas', unit:'st', std:3},
  {id:66, name:'Cheddar', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:67, name:'Chevre naturel', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:68, name:'Chevre honing', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:69, name:'Korstloze komijn', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:70, name:'Rookkaas naturel', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:71, name:'Feta geit', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:72, name:'Feta schaap', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:73, name:'Raclette', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:74, name:'Kernhemmer', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:75, name:'Bleu de Grave', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:76, name:'Geiten hommage blauw', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:77, name:'Zwitserse bergkaas', cat:'Buitenlandse kaas', unit:'st', std:3},
  {id:78, name:'Manchego', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:79, name:'Manchego truffel', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:80, name:'Pecorino romano', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:81, name:'Pecorino Truffel', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:82, name:'Reggiano', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:83, name:'Parmesan', cat:'Buitenlandse kaas', unit:'¼', std:0},
  {id:84, name:'Comté 8 mnd', cat:'Buitenlandse kaas', unit:'spie', std:0},
  {id:85, name:'Comté 18 mnd', cat:'Buitenlandse kaas', unit:'spie', std:0},
  {id:86, name:'Emmenthaler', cat:'Buitenlandse kaas', unit:'spie', std:0},
  {id:87, name:'Vijgenbrood CHOCOLADE', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:88, name:'Dadelbrood WALNOOT', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:89, name:'Vijgenbrood AMANDEL', cat:'Buitenlandse kaas', unit:'st', std:1},
  {id:90, name:'Buffel mozzarella', cat:'Buitenlandse kaas', unit:'st', std:30},
  {id:91, name:'Burrata', cat:'Buitenlandse kaas', unit:'st', std:16},
  {id:92, name:'Halloumi', cat:'Buitenlandse kaas', unit:'st', std:10},
  {id:93, name:'Mascarpone', cat:'Buitenlandse kaas', unit:'st', std:8},
  {id:94, name:'Creme fraiche', cat:'Buitenlandse kaas', unit:'st', std:12},
  {id:95, name:'Ricotta', cat:'Buitenlandse kaas', unit:'st', std:8},
  {id:96, name:'Weideboter pakje 20st', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:97, name:'Roomboter rol gezouten', cat:'Buitenlandse kaas', unit:'st', std:10},
  {id:98, name:'Bakcamembert', cat:'Buitenlandse kaas', unit:'st', std:8},
  {id:99, name:'Kaasfondue 400 gram', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:100, name:'Verse kaasfondue geraspt VERS!!', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:101, name:'La bouygette', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:102, name:'La Tur', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:103, name:'St. Maure de Tourain', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:104, name:'Langres', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:105, name:'Figou', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:106, name:'Geit peper', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:107, name:'Vacherin 500 gram', cat:'Buitenlandse kaas', unit:'st', std:10},
  {id:108, name:'Vacherin mont d\'or', cat:'Buitenlandse kaas', unit:'st', std:2},
  {id:109, name:'Geraspt kaas extra belegen', cat:'Buitenlandse kaas', unit:'st', std:10},
  {id:110, name:'Geraspt Parmezaan', cat:'Buitenlandse kaas', unit:'st', std:15},
  {id:111, name:'Smeerkaas 20+', cat:'Buitenlandse kaas', unit:'st', std:6},
  {id:112, name:'Smeerkaas 48+', cat:'Buitenlandse kaas', unit:'st', std:6},
  {id:113, name:'Smeerkaas geit', cat:'Buitenlandse kaas', unit:'st', std:6},
  {id:114, name:'Parmersan bus 250 gr.', cat:'Buitenlandse kaas', unit:'st', std:4},
  {id:115, name:'Geska strooier', cat:'Buitenlandse kaas', unit:'st', std:5},
  {id:116, name:'Perzik/Gember', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:117, name:'HoningMosterd', cat:'Buitenlandse kaas', unit:'st', std:0},
  {id:118, name:'Mosterd/dille saus', cat:'Buitenlandse kaas', unit:'st', std:12},
  {id:119, name:'Vijgendip', cat:'Buitenlandse kaas', unit:'doos', std:0},
  {id:120, name:'2 voor €5 Kruidenkaas', cat:'Overig', unit:'krat', std:0},
  {id:121, name:'Buitenlandse kaas 3 voor €5 (BAK)', cat:'Overig', unit:'st', std:0},
  {id:122, name:'8,95 vacuumkaas', cat:'Overig', unit:'krat', std:0},
  {id:123, name:'Boerderij eieren KRAT', cat:'Overig', unit:'krat', std:20},
  {id:124, name:'Biologische eieren KRAT', cat:'Overig', unit:'krat', std:1},
  {id:125, name:'Cider (3 soorten)', cat:'Overig', unit:'doos', std:0},
  {id:126, name:'Kaasschaven lang', cat:'Non food', unit:'st', std:0},
  {id:127, name:'Kaasschaven rasp', cat:'Non food', unit:'st', std:0},
  {id:128, name:'Bakjes + deksels KLEIN', cat:'Non food', unit:'krat', std:0},
  {id:129, name:'Bakjes + deksels GROOT', cat:'Non food', unit:'krat', std:0},
  {id:130, name:'Klein papier', cat:'Non food', unit:'st', std:0},
  {id:131, name:'Groot papier', cat:'Non food', unit:'st', std:0},
  {id:132, name:'Kaaszakjes', cat:'Non food', unit:'doos', std:0},
  {id:133, name:'Vacuüm zakken KLEIN', cat:'Non food', unit:'st', std:0},
  {id:134, name:'Vacuüm zakken MIDDEL', cat:'Non food', unit:'st', std:0},
  {id:135, name:'Vacuüm zakken GROOT', cat:'Non food', unit:'st', std:0},
  {id:136, name:'Folie rollen', cat:'Non food', unit:'doos', std:0},
  {id:137, name:'Papieren tassen', cat:'Non food', unit:'doos', std:0},
  {id:138, name:'Hanschoenen', cat:'Non food', unit:'st', std:0},
  {id:139, name:'Draadjes', cat:'Non food', unit:'st', std:4},
  {id:140, name:'Doeken', cat:'Non food', unit:'st', std:0},
  {id:141, name:'Pinrollen', cat:'Non food', unit:'st', std:2},
  {id:142, name:'Kassa rollen', cat:'Non food', unit:'st', std:4},
  {id:143, name:'Flessen water', cat:'Non food', unit:'st', std:0},
  {id:144, name:'Suiker', cat:'Non food', unit:'st', std:0},
  {id:145, name:'Melk', cat:'Non food', unit:'st', std:0},
  {id:146, name:'Koffie', cat:'Non food', unit:'st', std:0},
  {id:147, name:'Cola', cat:'Non food', unit:'st', std:0},
  {id:148, name:'Schorten', cat:'Non food', unit:'st', std:0},
  {id:149, name:'Grote tafel', cat:'Non food', unit:'st', std:0},
  {id:150, name:'Kassa Kraam', cat:'Non food', unit:'st', std:0},
  {id:151, name:'Marktbestelling', cat:'Non food', unit:'st', std:0},
];

const DEFAULT_PRODUCTS_W2 = [

  {id:2001, name:'Jonge kaas',                    cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2002, name:'Zacht belegen',                 cat:'Hollandse kaas', unit:'st',   std:3},
  {id:2003, name:'NH belegen',                    cat:'Hollandse kaas', unit:'st',   std:4},
  {id:2004, name:'Extra belegen excellent',       cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2005, name:'Oude dorpkaas',                 cat:'Hollandse kaas', unit:'st',   std:6},
  {id:2006, name:'Brokkel kaas',                  cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2007, name:'Old special',                   cat:'Hollandse kaas', unit:'st',   std:5},
  {id:2008, name:'Kaas van de week',              cat:'Hollandse kaas', unit:'st',   std:3},
  {id:2009, name:'Komijn jong',                   cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2010, name:'Komijn belegen',                cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2011, name:'Komijn oud',                    cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2012, name:'Nagel kaas',                    cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2013, name:'Brokkel komijn',                cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2014, name:'Boeren jong belegen',           cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2015, name:'Boeren belegen',                cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2016, name:'Boeren Grand Cru',              cat:'Hollandse kaas', unit:'st',   std:8},
  {id:2017, name:'Boeren oud',                    cat:'Hollandse kaas', unit:'¼',    std:1},
  {id:2018, name:'Tijnjethaler',                  cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2019, name:'Boeren Leids 20+ zacht & exbel',cat:'Hollandse kaas', unit:'st',  std:1},
  {id:2020, name:'Seizoenskaas',                  cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2021, name:'30+ zacht',                     cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2022, name:'Gouwenaar 30+ pittig',          cat:'Hollandse kaas', unit:'st',   std:8},
  {id:2023, name:'30+ extra gerijpt',             cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2024, name:'Maasdammer',                    cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2025, name:'Kinderdijk bio belegen',        cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2026, name:'Kinderdijk bio extra belegen',  cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2027, name:'Sedurre',                       cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2028, name:'Fenegriek',                     cat:'Hollandse kaas', unit:'¼',    std:1},
  {id:2029, name:'Mosterd',                       cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2030, name:'Truffelkaas',                   cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2031, name:'Pestokaas rood/groen',          cat:'Hollandse kaas', unit:'st',   std:1},

  {id:2032, name:'Geitenkaas Aktie',              cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2033, name:'Geitenkaas pittig belegen',     cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2034, name:'Geitenkaas oud',                cat:'Hollandse kaas', unit:'st',   std:2},
  {id:2035, name:'Bio geitenkaas',                cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2036, name:'30+ geitenkaas',                cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2037, name:'Geit brandnetel + fenegriek + ital.', cat:'Hollandse kaas', unit:'st', std:1},
  {id:2038, name:'Schapenkaas (goed!)',           cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2039, name:'Schapenkaas oud',               cat:'Hollandse kaas', unit:'st',   std:1},
  {id:2040, name:'Geit blauw',                    cat:'Hollandse kaas', unit:'½',    std:1},
  {id:2041, name:'Geit truffel',                  cat:'Hollandse kaas', unit:'st',   std:1},

  {id:2042, name:'Buffel mozzarella',             cat:'Buitenlandse kaas', unit:'st',  std:4},
  {id:2043, name:'Koe mozzarella',                cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2044, name:'Burrata',                       cat:'Buitenlandse kaas', unit:'st',  std:8},
  {id:2045, name:'Mosterd/dille saus',            cat:'Buitenlandse kaas', unit:'st',  std:6},
  {id:2046, name:'Korstloze komijn',              cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2047, name:'Halloumi',                      cat:'Buitenlandse kaas', unit:'st',  std:6},
  {id:2048, name:'Cheddar',                       cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2049, name:'Dadelbroodjes 200gr',           cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2050, name:'Rookkaas',                      cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2051, name:'Geitenfeta',                    cat:'Buitenlandse kaas', unit:'st',  std:3},
  {id:2052, name:'Feta schaap',                   cat:'Buitenlandse kaas', unit:'blok',std:1},
  {id:2053, name:'La bouygette',                  cat:'Buitenlandse kaas', unit:'kist',std:3},
  {id:2054, name:'Langres',                       cat:'Buitenlandse kaas', unit:'kist',std:3},
  {id:2055, name:'Chevre as',                     cat:'Buitenlandse kaas', unit:'kist',std:3},
  {id:2056, name:'La tur',                        cat:'Buitenlandse kaas', unit:'kist',std:1},
  {id:2057, name:'Meikaas',                       cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2058, name:'Bergkaas',                      cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2059, name:'Gruyere',                       cat:'Buitenlandse kaas', unit:'spie',std:1},
  {id:2060, name:'Gruyere oud',                   cat:'Buitenlandse kaas', unit:'spie',std:1},
  {id:2061, name:'Emmentaler',                    cat:'Buitenlandse kaas', unit:'spie',std:1},
  {id:2062, name:'Manchego',                      cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2063, name:'Parmesan',                      cat:'Buitenlandse kaas', unit:'¼',   std:1},
  {id:2064, name:'Parmesan reggiano',             cat:'Buitenlandse kaas', unit:'¼',   std:1},
  {id:2065, name:'Manchego truffel',              cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2066, name:'Pecorino romano',               cat:'Buitenlandse kaas', unit:'spie',std:1},
  {id:2067, name:'Morbier',                       cat:'Buitenlandse kaas', unit:'¼',   std:1},
  {id:2068, name:'Raclette',                      cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2069, name:'Bleu de Grave',                 cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2070, name:'Vacherin mont d\'or',           cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2071, name:'Honing klaver',                 cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2072, name:'St Agur',                       cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2073, name:'Schepgorgonzola',               cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2074, name:'Delice de Bourgogne',           cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2075, name:'Epoise coupe',                  cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2076, name:'Roombrie',                      cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2077, name:'Boerenbrie',                    cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2078, name:'Zwitserse strooiers',           cat:'Buitenlandse kaas', unit:'st',  std:4},
  {id:2079, name:'Kaasfondue',                    cat:'Buitenlandse kaas', unit:'st',  std:8},
  {id:2080, name:'Boeren smeerkaas 20+',          cat:'Buitenlandse kaas', unit:'st',  std:4},
  {id:2081, name:'Gemalen kaas vers',             cat:'Buitenlandse kaas', unit:'st',  std:4},
  {id:2082, name:'Gemalen kaas Parmazaan',        cat:'Buitenlandse kaas', unit:'st',  std:6},
  {id:2083, name:'Buitenlandse kaas 3 stuks voor 5', cat:'Buitenlandse kaas', unit:'bak', std:1},

  {id:2084, name:'Rauwmelks BIO',                 cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2085, name:'Specialiteiten €6,95',          cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2086, name:'Bakcamembert',                  cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2087, name:'Brie de Meaux',                 cat:'Buitenlandse kaas', unit:'st',  std:1},
  {id:2088, name:'Cider (1 doos rood, 1 doos groen)', cat:'Overig',        unit:'doos',std:2},
  {id:2089, name:'Jubileumkaas',                  cat:'Hollandse kaas',    unit:'st',  std:1},
  {id:2090, name:'Gesneden oud NH',               cat:'Hollandse kaas',    unit:'st',  std:1},

  {id:2091, name:'Edammers',                      cat:'Overig', unit:'st',   std:4},
  {id:2092, name:'Bio eieren',                    cat:'Overig', unit:'doos', std:1},
  {id:2093, name:'Boerderij eieren',              cat:'Overig', unit:'krat', std:7},
  {id:2094, name:'Roomboter pakje 10 st.',        cat:'Overig', unit:'ds',   std:20},
  {id:2095, name:'Roomboter rol gezouten',        cat:'Overig', unit:'st',   std:3},
  {id:2096, name:'Kruiden kazen 2 voor 5,00',     cat:'Overig', unit:'krat', std:1},
  {id:2097, name:'Pavesi crackers',               cat:'Overig', unit:'st',   std:1},
  {id:2098, name:'Olijven',                       cat:'Overig', unit:'st',   std:1},
  {id:2099, name:'Tapenade groen',                cat:'Overig', unit:'st',   std:1},
  {id:2100, name:'Tapenade 3 colore',             cat:'Overig', unit:'st',   std:1},
  {id:2101, name:'Maaslander',                    cat:'Overig', unit:'kg',   std:3},
  {id:2102, name:'Milde Schermer',                cat:'Overig', unit:'kg',   std:3},

  {id:2103, name:'Groot papier',                  cat:'Non food', unit:'pak',   std:1},
  {id:2104, name:'Klein papier',                  cat:'Non food', unit:'pak',   std:1},
  {id:2105, name:'Kaaszakjes',                    cat:'Non food', unit:'doos',  std:1},
  {id:2106, name:'Folie rollen',                  cat:'Non food', unit:'doos',  std:1},
  {id:2107, name:'Plastic tassen',                cat:'Non food', unit:'handje',std:1},
  {id:2108, name:'Kassa rollen',                  cat:'Non food', unit:'st',    std:1},
  {id:2109, name:'Pinrol',                        cat:'Non food', unit:'st',    std:1},
  {id:2110, name:'Draadjes',                      cat:'Non food', unit:'st',    std:3},
  {id:2111, name:'Doeken',                        cat:'Non food', unit:'st',    std:2},
  {id:2112, name:'Vacuumzak groot',               cat:'Non food', unit:'pak',   std:1},
  {id:2113, name:'Vacuumzak middel',              cat:'Non food', unit:'pak',   std:1},
  {id:2114, name:'Vacuumzak klein',               cat:'Non food', unit:'pak',   std:1},
  {id:2115, name:'Kassa',                         cat:'Non food', unit:'st',    std:1},
  {id:2116, name:'Pin',                           cat:'Non food', unit:'st',    std:2},
  {id:2117, name:'Cola',                          cat:'Non food', unit:'st',    std:1},
  {id:2118, name:'Schorten',                      cat:'Non food', unit:'st',    std:1},
  {id:2119, name:'Lege kratten',                  cat:'Non food', unit:'groot', std:8},
  {id:2120, name:'Parasols',                      cat:'Non food', unit:'st',    std:3},
  {id:2121, name:'Oude dorpkaas planken',         cat:'Non food', unit:'st',    std:1},
  {id:2122, name:'Statafels',                     cat:'Non food', unit:'st',    std:1},
  {id:2123, name:'Steekkar',                      cat:'Non food', unit:'st',    std:1},
  {id:2124, name:'Schragen',                      cat:'Non food', unit:'st',    std:1},
  {id:2125, name:'Reclamebord broodjes',          cat:'Non food', unit:'st',    std:1},
];